"""
Django settings for learningWeb project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
# 服务器开发使用
import os
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']
# SECRET_KEY = '+2&_^w3dm^87f$%xy^dj&@&j4a(8+q5f2ug2j$l$0ziv=!9y_8'
# jg-!inzi5w-(=u#n4c_+5t@e)l*89@b06+&eua1q4#zgzm7bo$

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# 服务器ip地址
ALLOWED_HOSTS = ['47.98.116.255']

DATABASES_PASSWORD = os.environ['DATABASES_PASSWORD']
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
# mima : 123456
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER':'ljw',
        'PASSWORD':DATABASES_PASSWORD,
        'HOST':'localhost',
        'PORT':'3306',
    }
}

# 发送邮箱设置
EMAIL_BACKED = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
# EMAIL_POST = 25 更换端口 阿里云需要添加一个465端口
EMAIL_POST = 465
EMAIL_HOST_USER = '1206957838@qq.com'
# os.environ['EMAIL_HOST_PASSWORD'] 'btbaedwwwtgijeia'
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']    # 授码权
EMAIL_SUBJECT_PREFIX = '[ ljw的博客 ]'
# EMAIL_USE_TLS = True      # SMTP通信时，是否启用 安全连接
EMAIL_USE_SSL = True # 开启安全连接ssl

# 配置管理员
ADMINS = (
    ('admin','1206957838@qq.com'),
)

# 日志文件
# 修改权限命令 文件可读可写，同组的人也是可读可写
# chmod 666
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/blog_debug.log',
        },
        # 发送邮件
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },

    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # 日志记录器
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

